#!/usr/bin/env python3
"""
verify_frozen.py - Mechanical lock verification for Super Tanks

Verifies that every frozen DIQ contract file matches the SHA-256 stored
in core/diq/DIQ_CHECKSUMS.json. Exits 0 on a clean repo, 1 on any
tampering / missing manifest / missing file.

Earlier versions pointed at core_locked/FROZEN_MANIFEST.json — a path
that doesn't exist in this codebase. The repo's actual integrity
system lives in core/diq/diq_integrity.py with DIQ_CHECKSUMS.json
generated by `diq_integrity.write_checksums()`. This script delegates
to that single source of truth.
"""

import hashlib
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DIQ_DIR = PROJECT_ROOT / "core" / "diq"
CHECKSUMS_FILE = DIQ_DIR / "DIQ_CHECKSUMS.json"


def calculate_sha256(filepath: Path) -> str:
    """SHA-256 of a file, streamed."""
    h = hashlib.sha256()
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            h.update(chunk)
    return h.hexdigest()


def verify_frozen() -> bool:
    """Verify every entry in DIQ_CHECKSUMS.json against on-disk SHA-256."""
    print("🔒 Super Tanks Frozen File Verification")
    print(f"   Manifest: {CHECKSUMS_FILE}")
    print()

    if not CHECKSUMS_FILE.exists():
        print("🔴 ERROR: DIQ_CHECKSUMS.json not found — manifest absent.")
        print("   Run `python -c 'from core.diq import diq_integrity; "
              "diq_integrity.write_checksums()'` to seal after validation.")
        return False

    try:
        manifest = json.loads(CHECKSUMS_FILE.read_text())
    except json.JSONDecodeError as exc:
        print(f"🔴 ERROR: DIQ_CHECKSUMS.json is corrupt: {exc}")
        return False

    all_valid = True
    for name, expected_hash in manifest.items():
        filepath = DIQ_DIR / name
        if not filepath.exists():
            print(f"🔴 MISSING: {name}")
            all_valid = False
            continue

        actual_hash = calculate_sha256(filepath)
        if actual_hash == expected_hash:
            print(f"✅ VALID: {name}")
        else:
            print(f"🔴 TAMPERED: {name}")
            print(f"   Expected: {expected_hash[:16]}...")
            print(f"   Actual:   {actual_hash[:16]}...")
            all_valid = False

    print()
    if all_valid:
        print("🔒 ALL FROZEN FILES VERIFIED — LOCK INTACT")
        return True
    print("🚨 TAMPERING DETECTED — DO NOT PROCEED")
    return False


if __name__ == "__main__":
    success = verify_frozen()
    sys.exit(0 if success else 1)
